name: CI

on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Upsert PR comment
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event_name == 'pull_request' }} ## Run on a pull request
        with:
          message: "Hello!"
          comment_includes: "Hello"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
